#!/usr/bin/env perl

use strict;
use warnings;

use P2JS::Converter;

my $filename = $ARGV[0];
my $script;
if ($filename) {
    open(my $fh, "<", $filename) or die("Cannot open $filename: $!");
    $script = do { local $/; <$fh> };
} else {
    $script = join('', <STDIN>);
}

print P2JS::Converter->new->convert($script);
